
import __ASTRO_IMAGE_IMPORT_Z1M5gMc from "/src/images/team/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fadrian-mcphee.md";
import __ASTRO_IMAGE_IMPORT_1IMuvF from "/src/images/team/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fkyriah-mcphee.md";
import __ASTRO_IMAGE_IMPORT_Z2vztSk from "/src/images/projects/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fbht-lme04-diversion-road-construction.md";
import __ASTRO_IMAGE_IMPORT_Z1Dp4j0 from "/src/images/projects/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fnorthern-revetment-wall-rehabilitation.md";
import __ASTRO_IMAGE_IMPORT_Z1Rrx34 from "/src/images/projects/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fparaburdoo-airport-asphalt-overlay.md";
import __ASTRO_IMAGE_IMPORT_1CBVk0 from "/src/images/services/management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fengineering-administration-and-project-support.md";
import __ASTRO_IMAGE_IMPORT_p8YHB from "/src/images/services/control.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fautomated-engineering-systems-and-qaqc-frameworks.md";
import __ASTRO_IMAGE_IMPORT_1u9Gc0 from "/src/images/services/structural.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fhealth-safety-and-environmental-systems.md";
import __ASTRO_IMAGE_IMPORT_Z29Lwoa from "/src/images/services/interior.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fiso-systems-and-audit-support.md";
import __ASTRO_IMAGE_IMPORT_StcMb from "/src/images/services/interior.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-close-out-services.md";
import __ASTRO_IMAGE_IMPORT_kdRfF from "/src/images/services/management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-familiarisation-and-delivery-tools.md";
import __ASTRO_IMAGE_IMPORT_Z2mbxD4 from "/src/images/services/preconstruction.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-start-up-services.md";
import __ASTRO_IMAGE_IMPORT_7W4SU from "/src/images/services/structural.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fshort-term-fill-ins-and-technical-support.md";
export default new Map([["/src/images/team/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fadrian-mcphee.md", __ASTRO_IMAGE_IMPORT_Z1M5gMc], ["/src/images/team/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fkyriah-mcphee.md", __ASTRO_IMAGE_IMPORT_1IMuvF], ["/src/images/projects/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fbht-lme04-diversion-road-construction.md", __ASTRO_IMAGE_IMPORT_Z2vztSk], ["/src/images/projects/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fnorthern-revetment-wall-rehabilitation.md", __ASTRO_IMAGE_IMPORT_Z1Dp4j0], ["/src/images/projects/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fparaburdoo-airport-asphalt-overlay.md", __ASTRO_IMAGE_IMPORT_Z1Rrx34], ["/src/images/services/management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fengineering-administration-and-project-support.md", __ASTRO_IMAGE_IMPORT_1CBVk0], ["/src/images/services/control.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fautomated-engineering-systems-and-qaqc-frameworks.md", __ASTRO_IMAGE_IMPORT_p8YHB], ["/src/images/services/structural.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fhealth-safety-and-environmental-systems.md", __ASTRO_IMAGE_IMPORT_1u9Gc0], ["/src/images/services/interior.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fiso-systems-and-audit-support.md", __ASTRO_IMAGE_IMPORT_Z29Lwoa], ["/src/images/services/interior.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-close-out-services.md", __ASTRO_IMAGE_IMPORT_StcMb], ["/src/images/services/management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-familiarisation-and-delivery-tools.md", __ASTRO_IMAGE_IMPORT_kdRfF], ["/src/images/services/preconstruction.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-start-up-services.md", __ASTRO_IMAGE_IMPORT_Z2mbxD4], ["/src/images/services/structural.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fshort-term-fill-ins-and-technical-support.md", __ASTRO_IMAGE_IMPORT_7W4SU]]);
		