
import __ASTRO_IMAGE_IMPORT_Z2nyUOM from "/src/images/adrian.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fadrian-mcphee.md";
import __ASTRO_IMAGE_IMPORT_2fdiIl from "/src/images/kyriah.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fkyriah-mcphee.md";
import __ASTRO_IMAGE_IMPORT_Z1LePvl from "./walking-staff.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fautomated-engineering-systems-and-qaqc-frameworks.md";
import __ASTRO_IMAGE_IMPORT_1CBVk0 from "/src/images/services/management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fengineering-administration-and-project-support.md";
import __ASTRO_IMAGE_IMPORT_Z29Lwoa from "/src/images/services/interior.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fiso-systems-and-audit-support.md";
import __ASTRO_IMAGE_IMPORT_kdRfF from "/src/images/services/management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-familiarisation-and-delivery-tools.md";
import __ASTRO_IMAGE_IMPORT_1u9Gc0 from "/src/images/services/structural.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fhealth-safety-and-environmental-systems.md";
import __ASTRO_IMAGE_IMPORT_StcMb from "/src/images/services/interior.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-close-out-services.md";
import __ASTRO_IMAGE_IMPORT_Z2mbxD4 from "/src/images/services/preconstruction.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-start-up-services.md";
import __ASTRO_IMAGE_IMPORT_Z28cX2O from "/src/images/paraburdoo-airport/WhatsApp Image 2025-10-27 at 05.44.04_dd560c4c.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fparaburdoo-airport-asphalt-overlay.md";
import __ASTRO_IMAGE_IMPORT_Z2vztSk from "/src/images/projects/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fbht-lme04-diversion-road-construction.md";
import __ASTRO_IMAGE_IMPORT_Z8LiNK from "/src/images/revetment-wall/DJI_0142.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fnorthern-revetment-wall-rehabilitation.md";
import __ASTRO_IMAGE_IMPORT_7W4SU from "/src/images/services/structural.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fshort-term-fill-ins-and-technical-support.md";
export default new Map([["/src/images/adrian.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fadrian-mcphee.md", __ASTRO_IMAGE_IMPORT_Z2nyUOM], ["/src/images/kyriah.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fkyriah-mcphee.md", __ASTRO_IMAGE_IMPORT_2fdiIl], ["./walking-staff.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fautomated-engineering-systems-and-qaqc-frameworks.md", __ASTRO_IMAGE_IMPORT_Z1LePvl], ["/src/images/services/management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fengineering-administration-and-project-support.md", __ASTRO_IMAGE_IMPORT_1CBVk0], ["/src/images/services/interior.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fiso-systems-and-audit-support.md", __ASTRO_IMAGE_IMPORT_Z29Lwoa], ["/src/images/services/management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-familiarisation-and-delivery-tools.md", __ASTRO_IMAGE_IMPORT_kdRfF], ["/src/images/services/structural.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fhealth-safety-and-environmental-systems.md", __ASTRO_IMAGE_IMPORT_1u9Gc0], ["/src/images/services/interior.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-close-out-services.md", __ASTRO_IMAGE_IMPORT_StcMb], ["/src/images/services/preconstruction.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fproject-start-up-services.md", __ASTRO_IMAGE_IMPORT_Z2mbxD4], ["/src/images/paraburdoo-airport/WhatsApp Image 2025-10-27 at 05.44.04_dd560c4c.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fparaburdoo-airport-asphalt-overlay.md", __ASTRO_IMAGE_IMPORT_Z28cX2O], ["/src/images/projects/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fbht-lme04-diversion-road-construction.md", __ASTRO_IMAGE_IMPORT_Z2vztSk], ["/src/images/revetment-wall/DJI_0142.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fnorthern-revetment-wall-rehabilitation.md", __ASTRO_IMAGE_IMPORT_Z8LiNK], ["/src/images/services/structural.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2Fshort-term-fill-ins-and-technical-support.md", __ASTRO_IMAGE_IMPORT_7W4SU]]);
		